// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maotcooymljrbmadlsxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hb3Rjb295bWxqcmJtYWRsc3h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NjM1NDcsImV4cCI6MjA3MjIzOTU0N30.mx9XYrEkrTZcB_hziBW4ZNoSHsqaixjzbcE-H1XQEIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});